import { IDENTITY_COLOR_LIFT } from './gl/pipeline'
import type { LineArtMode, LineArtParams } from './types'

/** Canonical list of the 7 shipped algorithms, in display order — shared by App.tsx and any lab
 * harness that needs to iterate every mode (e.g. seeding one params object per algorithm) without
 * re-deriving the list locally. See CLAUDE.md's Recurring Gotchas: this project has repeatedly
 * paid for the same fact being duplicated in more than one place and drifting. */
export const LINE_ART_MODES: LineArtMode[] = ['pathB', 'pathC', 'pathD', 'pathF', 'pathG', 'pathH', 'pathI']

/** Cosmetic display names, keyed by internal mode id — shared by LineArtPanel's algo selector and
 * App.tsx's dev-only state dump (src/debug/dumpState.ts), which both need the same human-readable
 * name without either owning the canonical list. */
export const LINE_ART_LABELS: Record<LineArtMode, string> = {
  pathB: 'Botan',
  pathC: 'Chie',
  pathD: 'Daiya',
  pathF: 'Fumiko',
  pathG: 'Gumi',
  pathH: 'Hinata',
  pathI: 'Tsukiko',
}

/** Per-algorithm default overrides — used both by LineArtPanel (when switching modes fresh) and App.tsx (to seed each algorithm's initial cached params, see the per-mode memory there). */
export const LINE_ART_MODE_DEFAULTS: Record<LineArtMode, Partial<LineArtParams>> = {
  pathB: {
    opacity: 1,
    threshold: 0,
    radius: 1,
    hardness: 1,
    blobContrast: 1,
    colorContrast: 1,
    tintColor: [0, 0, 0],
    fillType: 'image',
    fillInvert: false,
  },
  pathC: {
    opacity: 1,
    gateThreshold: 0.05,
    radius: 1,
    hardness: 1,
    fillType: 'solid',
    tintColor: [0, 0, 0],
    fillInvert: false,
  },
  pathD: {
    opacity: 0.94,
    threshold: 0.6,
    radius: 2,
    hardness: 0,
    colorContrast: 1.04,
    tintColor: [1, 0.475, 0.886],
    vividDeadzone: 0.15,
    vividBoost: 1,
    fillType: 'image',
    fillInvert: false,
  },
  pathF: {
    opacity: 1,
    sensitivity: 3,
    radius: 0.2,
    findEdge: true,
    saturation: 0.5,
    hardness: 0,
    tintColor: [1, 0.475, 0.886],
    vividDeadzone: 0.15,
    vividBoost: 1,
    fillType: 'image',
    fillInvert: false,
  },
  pathG: {
    opacity: 1,
    threshold: 0.5,
    radius: 1,
    blobContrast: 1,
    colorExpansion: false,
    colorContrast: 1,
    tintColor: [0, 0, 0],
    gumiContrastBoost: 1,
    blobMaxDt: 2,
    gumiOverdrive: 0,
    gumiLineFillType: 'solid',
    gumiLineSolidColor: [0, 0, 0],
    gumiLineInvert: false,
    // Not exposed in the UI — frozen off, keeping the pipeline branch dormant/revivable rather
    // than removing the code.
    gumiGapClosing: false,
    // Top-hat cleanup prototype — lab-only control surface (LabZoneApp.tsx's Gumi panel), not yet
    // a production slider. See types.ts's gumiTopHatMode doc comment.
    gumiTopHatMode: false,
    gumiTopHatRadius: 2,
    gumiBlobGamma: 1,
    gumiColorBleed: false,
    gumiBleedFeather: 1.5,
    gumiBleedRadius: 8,
    gumiSoftDetection: false,
    gumiSoftness: 0.1,
    gumiFillMode: false,
    gumiFillRadius: 8,
    gumiFillInvert: false,
    gumiFillType: 'image',
    gumiFillSolidColor: [0, 0, 0],
    gumiFillPixelThreshold: false,
    gumiGradientMap: false,
    gumiGradientShadow: [0, 0, 0],
    gumiGradientMid: [0.5, 0.5, 0.5],
    gumiGradientHighlight: [1, 1, 1],
    gumiDualLine: false,
    gumiDualBlack: { position: 0.2, expand: 0.3, feathering: 0.15 },
    gumiDualWhite: { position: 0.8, expand: 0.3, feathering: 0.15 },
    gumiDualBlackFillType: 'solid',
    gumiDualBlackSolidColor: [0, 0, 0],
    gumiDualBlackInvert: false,
    gumiDualWhiteFillType: 'solid',
    gumiDualWhiteSolidColor: [1, 1, 1],
    gumiDualWhiteInvert: false,
    gumiDualWhiteOnTop: true,
    gumiLineColorContrast: 1,
    gumiLineGradientPivot: 0,
    gumiFillColorContrast: 1,
    gumiFillGradientPivot: 0,
    gumiDualBlackColorContrast: 1,
    gumiDualWhiteColorContrast: 1,
  },
  pathH: {
    // Default treatment is Edge (highPassResponsiveColor: true); both polarities sample from the
    // artwork.
    opacity: 1,
    threshold: 0.48,
    radius: 2,
    thresholdEnabled: false,
    hiToneTarget: 'off',
    hiToneGain: 1,
    hiToneContrast: 1,
    hiRawDarkenLighten: 0,
    hiThresholdContrast: 1,
    hiRawContrast: 1,
    hiToneSaturation: 1,
    hiToneHueInvert: false,
    hiThresholdInvert: false,
    highPassStrength: 4,
    highPassResponsiveColor: true,
    responsiveCrossover: 0.5,
    responsiveGrow: 0,
    responsiveGrowBias: 0,
    edgeInkOverDarkFillType: 'image',
    edgeInkOverLightFillType: 'image',
  },
  pathI: {
    // Default treatment is Emboss, with a Darken/Lighten + Contrast push and a pre-blurred
    // Laplacian response.
    opacity: 1,
    threshold: 0.48,
    radius: 1.5,
    thresholdEnabled: false,
    hiToneTarget: 'off',
    hiToneGain: 1,
    hiToneContrast: 1,
    hiRawDarkenLighten: 0.5,
    hiThresholdContrast: 1,
    hiRawContrast: 1.62,
    hiToneSaturation: 1,
    hiToneHueInvert: false,
    hiThresholdInvert: false,
    highPassResponsiveColor: false,
    responsiveCrossover: 0.5,
    responsiveGrow: 0,
    responsiveGrowBias: 0,
    edgeInkOverDarkFillType: 'solid',
    edgeInkOverDarkSolidColor: [0, 0, 0],
    edgeInkOverLightFillType: 'solid',
    edgeInkOverLightSolidColor: [0, 0, 0],
    laplacianStrength: 3,
    laplacianPreBlur: 0.7,
    laplacianSharpenAmount: 0.55,
    laplacianGrow: 0,
  },
}

/** Full flat LineArtParams default — every field the interface declares, at App.tsx's own
 * from-scratch starting values. Overridden per-algorithm by LINE_ART_MODE_DEFAULTS above via
 * buildDefaultParams(). Moved here (out of App.tsx) so any lab harness driving the real
 * production Pipeline directly gets the exact same starting object App.tsx does, rather than a
 * hand-copied duplicate that can drift — see CLAUDE.md's Recurring Gotchas on lab/production
 * mismatches. */
const BASE_LINE_ART_PARAMS: LineArtParams = {
  mode: 'pathB',
  displayMode: 'composite',
  toneShaping: {
    exposure: 0,
    contrast: 0,
    mode: 'clip',
    clipMode: { blackClip: 0, whiteClip: 1 },
    pinchMode: { position: 0.5, expand: 0.3, feathering: 0.5 },
  },
  denoise: { intensity: 0, threshold: 0 },
  colorLift: IDENTITY_COLOR_LIFT,
  opacity: 1,
  blendMode: 'multiply',
  overlayPassthrough: false,
  matteColor: [1, 1, 1],
  colorCorrectEnabled: false,
  colorCorrectExposure: 0,
  colorCorrectContrast: 0,
  colorCorrectSaturation: 0,
  colorCorrectInvertMatte: false,
  threshold: 0,
  radius: 1,
  hardness: 1,
  blobContrast: 1,
  daiyaOctagonMode: false,
  daiyaOctagonRadius: 2,
  daiyaOctagonHardness: 0,
  daiyaOctagonDirections: 1,
  daiyaOctagonRotation: 0,
  daiyaOctagonOneSided: false,
  daiyaInvertSeed: false,
  daiyaSoftThresholdWidth: 0,
  daiyaSoftThresholdOverdrive: 1,
  colorExpansion: false,
  colorContrast: 1,
  gateThreshold: 0,
  sensitivity: 3,
  saturation: 0.5,
  findEdge: false,
  tintColor: [1, 0.475, 0.886],
  vividDeadzone: 0.15,
  vividBoost: 1,
  fillType: 'image',
  fillInvert: false,
  gradientShadow: [0, 0, 0],
  gradientMid: [0.5, 0.5, 0.5],
  gradientHighlight: [1, 1, 1],
  gradientPivot: 0,
  gradientDuoTone: false,
  gumiContrastBoost: 1,
  blobMaxDt: 8,
  gumiOverdrive: 0,
  gumiLineFillType: 'solid',
  gumiLineSolidColor: [0, 0, 0],
  gumiLineInvert: false,
  gumiGapClosing: false,
  gumiTopHatMode: false,
  gumiTopHatRadius: 2,
  gumiBlobGamma: 1,
  gumiColorBleed: false,
  gumiBleedFeather: 1.5,
  gumiBleedRadius: 8,
  gumiSoftDetection: false,
  gumiSoftness: 0.1,
  gumiFillMode: false,
  gumiFillRadius: 8,
  gumiFillInvert: false,
  gumiFillType: 'image',
  gumiFillSolidColor: [0, 0, 0],
  gumiFillPixelThreshold: false,
  gumiGradientMap: false,
  gumiGradientShadow: [0, 0, 0],
  gumiGradientMid: [0.5, 0.5, 0.5],
  gumiGradientHighlight: [1, 1, 1],
  gumiDualLine: false,
  gumiDualBlack: { position: 0.2, expand: 0.3, feathering: 0.15 },
  gumiDualWhite: { position: 0.8, expand: 0.3, feathering: 0.15 },
  gumiDualBlackFillType: 'solid',
  gumiDualBlackSolidColor: [0, 0, 0],
  gumiDualBlackInvert: false,
  gumiDualWhiteFillType: 'solid',
  gumiDualWhiteSolidColor: [1, 1, 1],
  gumiDualWhiteInvert: false,
  gumiDualWhiteOnTop: true,
  gumiLineColorContrast: 1,
  gumiLineGradientPivot: 0,
  gumiFillColorContrast: 1,
  gumiFillGradientPivot: 0,
  gumiDualBlackColorContrast: 1,
  gumiDualWhiteColorContrast: 1,
  thresholdEnabled: false,
  hiToneTarget: 'off',
  hiToneGain: 1,
  hiToneContrast: 1,
  hiRawDarkenLighten: 0,
  hiThresholdContrast: 1,
  hiRawContrast: 1,
  hiToneSaturation: 1,
  hiToneHueInvert: false,
  hiThresholdInvert: false,
  highPassStrength: 1,
  highPassResponsiveColor: false,
  responsiveCrossover: 0.5,
  responsiveGrow: 0,
  responsiveGrowBias: 0,
  edgeInkOverDarkFillType: 'solid',
  edgeInkOverDarkSolidColor: [0, 0, 0],
  edgeInkOverDarkColorContrast: 1,
  edgeInkOverDarkExposure: 0,
  edgeInkOverLightFillType: 'solid',
  edgeInkOverLightSolidColor: [0, 0, 0],
  edgeInkOverLightColorContrast: 1,
  edgeInkOverLightExposure: 0,
  edgeDuoTone: false,
  edgeInvertFill: false,
  laplacianStrength: 1,
  laplacianPreBlur: 0,
  laplacianSharpenAmount: 0,
  laplacianGrow: 0,
}

export function buildDefaultParams(mode: LineArtMode): LineArtParams {
  return { ...BASE_LINE_ART_PARAMS, mode, ...LINE_ART_MODE_DEFAULTS[mode] }
}

/** One independent params object per algorithm — so tweaking Botan, switching to Chie, and
 * switching back doesn't lose Botan's edits (each mode remembers its own values until page
 * refresh/reset). displayMode is deliberately NOT included per-mode; callers that need it as a
 * global viewport toggle keep it outside this map (see App.tsx's own lineArtDisplayMode state). */
export function buildInitialParamsByMode(): Record<LineArtMode, LineArtParams> {
  const byMode = {} as Record<LineArtMode, LineArtParams>
  for (const mode of LINE_ART_MODES) {
    byMode[mode] = buildDefaultParams(mode)
  }
  return byMode
}
